version: '3'
services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - DOCKER=true
      - TZ=America/Denver
    volumes:
      - ~/Developer/turnip-bot:/db
networks:
  default:
    # Use a custom driver
    external:
      name: docker_default
