version: '3'
services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - DOCKER=true
      - TZ=America/Denver
    volumes:
      - ~/Developer/turnip-bot:/db
